### ISSUE TITLE
Death Laser Emitter Collider Too Big?

### ISSUE THREAD

**Issue by kadams8670** [Streus/Time-Is-Not#113]
There is a problem in level 4 (with the 3 hermit crab and switches puzzle) where you should be able to move a push block left so it sits in front of a death laser. However, the current collider setup blocks it, forcing you to push it up slightly. This really shouldn't happen given the current visuals.

**Comment by The-Alhooness** [comment]
Made the death laser colliders smaller to match sprite (also added in sprite orientation corrector to the emitter pieces)
