### ISSUE TITLE
Stasis bullet is colliding with things it shouldn't be

### ISSUE THREAD

**Issue by jestill2018** [Streus/Time-Is-Not#12]
The Stasis Bullet currently will sometimes collide with the player upon being instantiated, and will thus expand on top of the player. Additionally, the stasis bullet also collides with other stasis fields.****

**Comment by Streus** [comment]
Cannot replicate bullet colliding with player.  Code currently ignores collision between player and their bullets.

Will get to work preventing bullets from colliding with stasis bubbles.
