### ISSUE TITLE
Implement (if wanted) security laser triggered screen flash

### ISSUE THREAD

**Issue by kadams8670** [Streus/Time-Is-Not#129]
There is a WIP effect that makes the screen flash (currently red) if a security laser is tripped. Figure out if art team wants this and implement it. 

Note: the current concern is that the red flash more closely resembles the red color of the death laser. This could potentially be fixed if the death laser gets a different material.

**Comment by thitchings14** [comment]
Effect works as intended, and is transparent enough to not blot out any nearby death lasers.
