### ISSUE TITLE
Dashing into walls breaks dash / world mechanics

### ISSUE THREAD

**Issue by zabbott** [Streus/Time-Is-Not#24]
Dashing into a wall gets you stuck on that wall. If you time tether out of it (the only way we've seen how to get out of it) you then are stuck in the dash state and can walk through pits and what not.

**Comment by thitchings14** [comment]
Raised this observation in a duplicate post, but issue seems to sort itself out after about a minute in most tests I've done. Shaking sprite leaves me to believe it may be a clipping issue, and hummingbirds completely ignore you, meaning the player's "body" may be stuck in the wall where they can't see.
