### ISSUE TITLE
Dashing into wall from side locks controls, both mouse and keyboard, for about a minute.

### ISSUE THREAD

**Issue by thitchings14** [Streus/Time-Is-Not#30]
May have something to do with a clipping issue with the wall, as the sprite is constantly shaking during it.

**Comment by thitchings14** [comment]
After testing, works from all directions, not just sides.

**Comment by Streus** [comment]
This is a duplicate of issue #24 .

**Comment by thitchings14** [comment]
My bad. Will close issue.
