### ISSUE TITLE
Hummingbird rotates 360 degrees when reaching pond before continuing to next point.

### ISSUE THREAD

**Issue by thitchings14** [Streus/Time-Is-Not#38]
Fairly consistent over multiple tests, but not enough to seem normal. Only happens when node is more than 3 space on the nave grid from the wall.

**Comment by Streus** [comment]
This is a known issue. As it stands, it's pretty minor, and is an artifact of the navigation algorithm and the fact that we're trying to turn a continuous space into a discrete one.  Planned updates to the navigation algorithm and data structure may change this.
