### ISSUE TITLE
Stasis shot effect is off in instantiation point

### ISSUE THREAD

**Issue by klockja** [Streus/Time-Is-Not#79]
When the stasis shot effect is played, it appears in the middle of the player instead of the player's gauntlet. This looks kinda strange.

**Comment by The-Alhooness** [comment]
Instantiation point is at the center of the player and always has been, if we want this to be different we will have to have something that frame by frame for every animation tracks the position of the arm to instantiate it at

**Comment by kadams8670** [comment]
This is a minor issue. Though it's super easy to add an offset (about 0.25f to the right) when it spawns, this will also mess up the bullet's movement towards its target.
